#!/bin/bash
#SBATCH --ntasks=186
#SBATCH --ntasks-per-node=48
#SBATCH --threads-per-core=1
#SBATCH --partition=allq
#SBATCH --nodes=4
#SBATCH -o job.%N.%j.out  # STDOUT
#SBATCH -e job.%N.%j.err  # STDERR
#SBATCH --job-name kimblip

module purge
module load development
module load dev2024
module load Anaconda/2023.09/gplates

echo $PYTHONPATH

which mpirun
mpirun -np 186 python Calc_SEIRF_components.py